export const planetData = {
  planetary_system: {
    caption:
      "Data about the planets of our solar system (Planetary facts taken from Nasa's Planetary Fact Sheet - Metric)",
    terrestrial_planets: [
      {
        name: "Mercury",
        mass: 0.33,
        diameter: 4879,
        density: 5427,
        gravity: 3.7,
        length_of_day: 4222.6,
        distance_from_sun: 57.9,
        mean_temperature: 167,
        number_of_moons: 0,
        notes: "Closest to the Sun",
      },
      {
        name: "Venus",
        mass: 4.87,
        diameter: 12104,
        density: 5243,
        gravity: 8.9,
        length_of_day: 2802.0,
        distance_from_sun: 108.2,
        mean_temperature: 464,
        number_of_moons: 0,
      },
      {
        name: "Earth",
        mass: 5.97,
        diameter: 12756,
        density: 5514,
        gravity: 9.8,
        length_of_day: 24.0,
        distance_from_sun: 149.6,
        mean_temperature: 15,
        number_of_moons: 1,
        notes: "Our world",
      },
      {
        name: "Mars",
        mass: 0.642,
        diameter: 6792,
        density: 3933,
        gravity: 3.7,
        length_of_day: 24.7,
        distance_from_sun: 227.9,
        mean_temperature: -65,
        number_of_moons: 2,
        notes: "The red planet",
      },
    ],
    jovian_planets: {
      gas_giants: [
        {
          name: "Jupiter",
          mass: 1898,
          diameter: 142984,
          density: 1326,
          gravity: 23.1,
          length_of_day: 9.9,
          distance_from_sun: 778.6,
          mean_temperature: -110,
          number_of_moons: 67,
          notes: "The largest planet",
        },
        {
          name: "Saturn",
          mass: 568,
          diameter: 120536,
          density: 687,
          gravity: 9.0,
          length_of_day: 10.7,
          distance_from_sun: 1433.5,
          mean_temperature: -140,
          number_of_moons: 62,
        },
      ],
      ice_giants: [
        {
          name: "Uranus",
          mass: 86.8,
          diameter: 51118,
          density: 1271,
          gravity: 8.7,
          length_of_day: 17.2,
          distance_from_sun: 2872.5,
          mean_temperature: -195,
          number_of_moons: 27,
        },
        {
          name: "Neptune",
          mass: 102,
          diameter: 49528,
          density: 1638,
          gravity: 11.0,
          length_of_day: 16.1,
          distance_from_sun: 4495.1,
          mean_temperature: -200,
          number_of_moons: 14,
        },
      ],
    },
    dwarf_planets: [
      {
        name: "Pluto",
        mass: 0.0146,
        diameter: 2370,
        density: 2095,
        gravity: 0.7,
        length_of_day: 153.3,
        distance_from_sun: 5906.4,
        mean_temperature: -225,
        number_of_moons: 5,
        notes:
          "Declassified as a planet in 2006, but this remains controversial. (Source: http://www.usatoday.com/story/tech/2014/10/02/pluto-planet-solar-system/16578959/)",
      },
    ],
  },
};
